# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Cross-language wire-compat test for per-request SAE specs.

The Rust frontend (`vllm-engine-core-client`) forwards ``sae_clamp_specs``
southbound as typed msgpack with **integer layer keys**.  This test pins the
exact bytes the Rust side produces and proves the Python engine-core decoder
accepts them into the typed :class:`SAEClampSpec` form.

The hex constant below is generated by the Rust wire test
``protocol::tests::sae_clamp_wire_hex_fixture_for_python_cross_compat`` in
``rust/src/engine-core-client/src/protocol/mod.rs``.  If the wire shape
changes, rerun that test with ``UPDATE_EXPECT=1`` and copy the refreshed hex
here.
"""

import msgspec

from vllm.config.sae_steering_types import SAEClampEntry, SAEClampSpec
from vllm.sampling_params import SamplingParams

# EngineCoreSamplingParams::for_test() carrying one SAE clamp spec:
# module "golden_gate", hook "post_block", layer 20,
# {feature_idx: 34, kind: "absolute", value: 5.0, only_if_active: False},
# phase "both".  Regenerated by the Rust test named in the module docstring.
RUST_SAE_CLAMP_PARAMS_HEX = (
    "8cab74656d7065726174757265ca3f800000a5746f705f70ca3f800000a5746f705f"
    "6b00aa6d61785f746f6b656e73ce00010000aa6d696e5f746f6b656e7300a56d696e"
    "5f70ca00000000b16672657175656e63795f70656e616c7479ca00000000b0707265"
    "73656e63655f70656e616c7479ca00000000b272657065746974696f6e5f70656e61"
    "6c7479ca3f800000ae73746f705f746f6b656e5f69647390b35f616c6c5f73746f70"
    "5f746f6b656e5f69647390af7361655f636c616d705f73706563739183ab6d6f6475"
    "6c655f6e616d65ab676f6c64656e5f67617465a6636c616d707381aa706f73745f62"
    "6c6f636b81149184ab666561747572655f69647822a46b696e64a86162736f6c7574"
    "65a576616c7565cb4014000000000000ae6f6e6c795f69665f616374697665c2a570"
    "68617365a4626f7468"
)


def _decode(hex_payload: str) -> SamplingParams:
    """Decode Rust-encoded msgpack with the same strict decoder engine-core
    uses for ``SamplingParams`` (no lenient str→int key coercion)."""
    return msgspec.msgpack.Decoder(SamplingParams).decode(bytes.fromhex(hex_payload))


class TestRustSaeWireCompat:
    def test_rust_clamp_spec_decodes_to_typed_form(self):
        params = _decode(RUST_SAE_CLAMP_PARAMS_HEX)

        assert params.sae_clamp_specs is not None
        assert len(params.sae_clamp_specs) == 1
        spec = params.sae_clamp_specs[0]
        assert isinstance(spec, SAEClampSpec)
        assert spec.module_name == "golden_gate"
        assert spec.phase == "both"

        # The Rust side must have encoded the layer key as a msgpack integer:
        # the strict decoder would reject a string key for ``dict[int, ...]``.
        assert set(spec.clamps.keys()) == {"post_block"}
        layer_map = spec.clamps["post_block"]
        assert set(layer_map.keys()) == {20}

        (entry,) = layer_map[20]
        assert isinstance(entry, SAEClampEntry)
        assert entry.feature_idx == 34
        assert entry.kind == "absolute"
        assert entry.value == 5.0
        assert entry.only_if_active is False

        # No full-reconstruction specs rode along on this fixture.
        assert params.sae_full_reconstruction_specs is None

    def test_rust_clamp_spec_affects_steering_config_hash(self):
        params = _decode(RUST_SAE_CLAMP_PARAMS_HEX)
        spec_free = SamplingParams(max_tokens=params.max_tokens)

        assert spec_free.sae_clamp_specs is None
        assert (
            params.prefill_steering_config_hash
            != spec_free.prefill_steering_config_hash
        )
